apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: public-stage

# deprecated
commonLabels:
  app: public-api
  team: devops

# labels:
# - pairs:
#     app: public-api
#     team: devops
#   includeSelectors: true

commonAnnotations:
  note: "Este es el ambiente de STAGE"

resources:
- ns.yaml
- ../../base


patches:
- target:
    kind: ConfigMap
    name: cm-private-api
  path: cm-patch.yaml

- target:
    kind: Ingress
    name: public-api
  path: ing-patch.yaml

- target:
    kind: Deployment
    name: public-api-replicas
  path: deploy-strategic-patch.yaml

images:
  - name: KUSTOMIZE-DEFINED
    newName: orellx/kubelabs_publicapi
    newTag: 1.0.1
